server:
  port: ${FORGE_API_PORT:8080}

spring:
  flyway:
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
